### ISSUE TITLE
Add To Category problem

### ISSUE THREAD

**Issue by renatoen** [andyjennings314/IMATTC#17]
When I create a new category and try to add a mission to that category nothing happens. If I refresh the page everything works again. I'm using Tampermonkey on Safari.

**Comment by andyjennings314** [comment]
Found the reason for this - when creating a new category, one data source needed to be updated, and wasn't. This has now been pushed in version 1.3.6, and missions can now be added to freshly-created categories.

@renatoen please get the latest version, check, and confirm.
