### ISSUE TITLE
Preview route not working

### ISSUE THREAD

**Issue by chamber** [andyjennings314/IMATTC#18]
Preview route doesnt show anything and brings up this error,

Ingress Mission Creator Tool body { background-color: #000; color: #fff; font-family: arial, helvetica, sans-serif; height: 100%; text-align: center; width: 100%; } #container { position: absolute; top: 100px; width: 100%; } #container p { font-weight: bold; margin-top: 20px; }
Niantic Project
Something is wrong. Please try again later.

**Comment by andyjennings314** [comment]
@chamber I know that the mission creator sometimes throws that error at other random junctures, so I just want to confirm when it's appearing exactly:
- Is it occurring now, after you've perhaps refreshed and/or cleared your cache?
- Are you trying to preview a mission route, or a banner route?
- Is it occurring for particular missions/banners, or any mission/banner you try to preview?

**Comment by andyjennings314** [comment]
@chamber to add to that: what is the state of the mission / missions you're trying to preview? Are they published, drafts, just submitted?

**Comment by chamber** [comment]
I just checked again and I  can actually view the route for banner missions that are fully online.

I cant view banner missions for ones that arent approved or banner missions that are partially approved.

**Comment by andyjennings314** [comment]
@chamber

That confirms it's related to an issue I've found: since unpublished missions don't have values for completion time, completion totals, and ratings, it crashes when trying to work with those numbers.

I've just made a fix to this with commit cb9d781aff6e9bf6e36920efb2ecd45ad78a45b1, please get the latest version of the script and see if this error is still occuring for you.

**Comment by chamber** [comment]
Still not showing for me. This commit seems to be for version 1.4.0, however the latest version showing on Tampermonkey was 1.4.1

**Comment by andyjennings314** [comment]
Closing due to lack of validation
