### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by mattyFRAICHE** [andyjennings314/IMATTC#40]
After loading the plugin, the whole page goes black and i can only access the drop menu from my agent name (which will sign me out) and the create mission button

![image](https://user-images.githubusercontent.com/42078911/70394729-b12d2900-19c5-11ea-94a7-1de74ca486e6.png)

**Comment by andyjennings314** [comment]
@mattyFRAICHE can you show me if you're getting any console errors?

**Comment by mattyFRAICHE** [comment]
I’m on a chromebook. How does one find this info for you?

**Comment by andyjennings314** [comment]
@mattyFRAICHE Open the mission editor in your browser, then when you've got the black screen, hit F12, and click whatever button says 'Console'. Print screen whatever text it has, and drop it in a comment here.

**Comment by andyjennings314** [comment]
@mattyFRAICHE this issue may be related to one other users have just raised. Please can you check and see if it's still occuring for you?

**Comment by mattyFRAICHE** [comment]
When I get home I can check. Work doesn’t allow chrome extensions so no tampermonkey.
