### ISSUE TITLE
Preview Route not working

### ISSUE THREAD

**Issue by ChopStiR** [andyjennings314/IMATTC#47]
Running Tampermonkey on Chrome.
Getting a pop up error straight away when selecting preview route. 
"An error occured (code = 0)"

**Comment by ChopStiR** [comment]
Just found it appears to be a bug when using the new web site missions.ingress.com
Had no issue when I just tested on the old beta missions page.

**Comment by andyjennings314** [comment]
The plugin was trying to call the API on the old betaspike page, which it didn't like. It's now been amended to use the API for whichever version of the site you're on. Good catch!
