### ISSUE TITLE
The title of the preview image says: Preview "false" or Preview "true"

### ISSUE THREAD

**Issue by ErreKrbo** [andyjennings314/IMATTC#55]
If I click in Preview Images in a Category, the new window has _Preview "true"_ in the title or _Preview "false"_ (depending the Category created
![Captura de pantalla 2021-09-24 a las 18 37 23](https://user-images.githubusercontent.com/7780256/134710553-569577b6-bd71-4b3e-88f9-065007cd6264.png)
)

**Comment by andyjennings314** [comment]
I am amazed that nobody, not even me, noticed this up until now. Easy to fix tho!

**Comment by andyjennings314** [comment]
This has been fixed with a quick update to the plugin - get the latest version and it should be working fine. Thanks for raising that!
